# Generated by Django 3.1.1 on 2020-09-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
